language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8.9.4

install:
  - npm install -g npm@5.6.0
  - npm install -g gulp
  - npm install

script:
  - gulp test --build --runInBand

before_deploy: if [ "$TRAVIS_BRANCH" == "release" ]; then gulp deploy --build -—production; fi

deploy:
  - provider: s3
    bucket: carbon.sage.com
    skip_cleanup: true
    local_dir: deploy
    on:
      branch: release
    access_key_id:
      secure: iZx7SkuMjUMXLVQNO5LSjF6EfQeqGbgdGtPg0hfzVIEcS5s/79j5aq8aQJ7EjCXM+yPRDZMaXB+StXOZjNhEbKLYt2mZDyMki3gAII2QM2MAeI5YtltgJHlXClsMjFiomTbRPo/F9CnIerRBdAFUmQXh2BVSdz86ptsLWs9SrcSjgN/RM6bWSaFYbyckyRVQZVipHYN1vmbEw8ZNZGSQTEPyi3Pw4nXMJ+9ro/72Pt5Ioo3a/praWJL9I5hEc6uBAfFZTtsg70txARaSOycoHxQT8S/xfIzfPQXSmj3n4MTMMCOi3CyJFJfTOdHnQ2ylSllae3zLgIJv1dPQoRuPrB0A1loG2BA+1PXA7KZrwBzYty20XMM2o2tB4mlkKh8p1gOjdsAyRT415kDkEvGpw/b+jFPQ+mAg67ELCJz/HTvBvrKF8nAGsoiG0A1Bi89wxi2riMjAZ2VzbTHrTq/Lp/MlJYt4Z44CXVSKXlKBVKwlDVS7+OIp5QAC0AggtJGFb4kvS/6zUnoykM/lsRBX99lsMURlpGq/EKC5B4iU26NWvF4L+sO9UUesN7LMr8C6oSc7wVrhLHiQbJx55UZTjT4+H/Y4VOFOiEhVKKJTk0/jt/QOOxZbuyhMitLOMBTQQ9tEICv7fIFSUIfePD3bG6FR3vXvod0ct/H7/DhNM0A=
    secret_access_key:
      secure: qdS1pq1ZXvw6lXLrGtSaZTpx7OLREvV/7UCwPFbfQkuQBLbxLe32qlzOkkEQWd7sHwadSgvVTKvX4HKaAIx+QZ2XXFbXGx4HIOCws6ynAVVa2kV5SSHKMwiy+R6Ypttu3GD6uKEhPMUULCYuCLzIIvAOKoCaDIzzKlxzK+g/tCe94J+fKU0DS6U23FFxW51UADgTxn7opg3mkhsteaRyAtDkurAeobEzfQpTFKPNXJ3YcFjpGUf9Z5zxcXXNohKZQP4wODgYU+OZuif/cAeETChWxVThk0PMIIk9/lmwyX1UKIpWpyVTDEKXzwnO2COVWOxtVCpTB0uwfZTZ8MhVXRvFj8Dk/iw+2NN/W55fQ44xx0h6mvhMle98jKTWi6AR/F0LJMpCkZeNTVCdiDz7Ow1g23HlBIRx/seYxph2vLSLkh63kU8ygaOFWhCNdCGOOPLHi8m8X8vlLRvN9ETWY/sMWkvY/S9bXIGw8lv5Bk4lIxAmjoU05XJceq5rOlSax46d1fsicJ5gF6tcxvMau2bFGMCgeZJEpRYChqTEt284woFc8+maa4SwMVrim6J8R53Xfx8mtgCnRlgZmXymzyxu8wCVnAza24iQ4kWmx+fDw70iU5Q3nxSwjN4Q922QZiAFLGpAK0nRDFhE7NPftubYOgsisNCFOnTTTBGJghI=
  - provider: npm
    email:
      secure: Ua66JoWgtTIzOlKBw+NzI9Ey6AE+D/+RExWdV5ZHldL0YUWn8RORWbFue7IkM//jKNRf2h8D8T2s+C7m4T4p12u1POC/waVqpkCrBvUvDevUpjf+fsMvt/OvsB0Sb2kcoI6Qo4YnxK/TZMkOyRvOxGkdKzWT/V92VpmcVmDllwpgeoE3xedGTogp51+fDUQ4oE9E7KtYJfGs9yN0+v6ZiNj2M1JG3/p0wV+wev2gGlvb862QZzbks1ulmYqsnx9rt4aBWGm9SPKqOTtaWUNQlVLOllBlsGUmN45OWAZHxJsxDo8Hp/f8/iK89YTXCpTq+tLDGkkrmPAMWSHKlCUaDDGNc9mmHlw6sM5kvWxcVpxZDgZyHS6I6K3/n1Dj7pVn+AGxQhjBPrw9eH9BzdVHmhQ/mNLG4hayS4tF7iO12s7QnjrcMf6pmNq49Y4M2gTSTN8s5RMzyO1HkTwN9uBca1yMm7Ay2RbnVBuOytLSI/W8KofGFW7N4gNVBWsW78YoVnczDt4qqWZcwX6J7xnScVNQav04qozC1u4NlGHlmtAzHQ1nEkGJIEW9leA0N1WIgdLPFqW5XjyxvlCuirvrj9rcrQ9WO+Dpo1I7ZtUyenprSmEG/f2+Z/C6J1CyDIeWONkLmW8rDyqDi3OgV85NfO18fG9RdrW5K2iqY6U6VN4=
    api_key:
      secure: "dsv9X9d7nBlibWJd4+2FpabOfOiBH4O9ANmAGqsxukJbYiA9Tp3x1wh9/Fp6O3kURUQE4+RkdoD+OVosZ4Ou7yk2thD62dCPdJagfqUARrzjNJ4xbE9xxxRHhWE+fVa6JqJqA0jFOfMPnaG4zvfbBcp0uQLKSsNqqo3CYRIoj0cvkRn6MLwmj5Fe52rUJic6TsTvDYxvLQaEEN3c0pR8BCTz6YlgRJbT0V8UIJpVYyRacLM31LnLOf6ab1nHQf1DrpKwa24lFHVEEiBl0nQB8GQzqxxNZhtg1Dt2v8krkm1WeOh56KzpBWdhdv5VR/DOXuuJTuCYFW1v0i9fKfWiqxPnCV7M2AYwgUhyup9LfaGcGJDITbBMdkKnOrxeISQPPrwf7O8SLWn9jzo4Dc5fZmsglfHN1p6ZkF1JdlEmcXXMHFpWkYntcUn390PZSLnysF39F5dtuSZpVbvvZXBjg5vqmoA5EBxFEAVOSh/HWOQNWAGZnrzDvpT0dxvY0a+sIum68VHUuz7rjVnuZpMb1qHn4EFV2MoMFAWigbQXySGsg6kBQGKhu8IAJMQp+KqcqJeLWYvFP6tEo/VMsQmaMSOoGtDl1gpJ21Ps9AgCGGiYJmeyCY43lWObEYQjcg3pu352Mxftk3ur18S45Ap/gJFIMjTVf6BmRUbSa1+KF7U="
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^((v[0-9]+.[0-9]+.[0-9]+)(-rc[0-9]+)?)$"
