version: '2.1'

services:
  cypress:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: carbon_cypress
    container_name: cypress
    command: bash -c 'npm run storybook-ci </dev/null &>/dev/null &'
    environment:
      CYPRESS_baseUrl: http://storybook:9001/