version: '2.1'

services:
  cypress:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: carbon_cypress
    container_name: cypress
    command: bash -c 'wait-on http://storybook:9001 && sleep 1000'
    environment:
      CYPRESS_baseUrl: http://storybook:9001/
    depends_on:
      - storybook
    # volumes:
    #   - './cypress/screenshots/:/usr/src/app/cypress/screenshots/'
  storybook:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: carbon_cypress
    container_name: storybook
    command: bash -c "npm run storybook-ci"